# Configuracao de execucao
server:
  port: 8080

spring:
  # Banco de dados
  datasource:
    url: "jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/lazuli?createDatabaseIfNotExist=false"
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123mudar}

  # JPA
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: none
    show-sql: false

  # Banner de inicializacao
  banner:
    location: assets/banner.txt

loggingfile:
  name: "logs/lazuli-logs.log"
  charset: "console=UTF-8"
  logback: "rollingpolicy.max-history=5"

springdoc:
  swagger-ui:
    path: swagger-ui.html
    disable-swagger-default-url: true
